// import Head from "next/head";
// export const metadata = {
//   title: 'Create Next App Design',
//   description: 'Generated by create next app',
// }

export default function DesignLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Transforming Ideas into Reality - My Page | Design</title>
        <meta
          name="description"
          content="Welcome to my studio, where creativity meets functionality! We are passionate about designing innovative and visually stunning solutions tailored to meet your unique needs. With our expert team of designers, we specialize in bringing ideas to life, ensuring every project is a masterpiece."
          key="desc"
        />
        <meta
          property="og:title"
          content="Transforming Ideas into Reality - My Page | Design"
        />
        <meta
          property="og:description"
          content="Welcome to my studio, where creativity meets functionality!"
        />
        <meta property="og:image" content="images/design_header.jpg" />
      </head>
      <body>{children}</body>
    </html>
  );
}
